# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blassoconditional <- function(Y, X, XtY, XtX, tau2, sigma2) {
    .Call('_debiasedmcmc_blassoconditional', PACKAGE = 'debiasedmcmc', Y, X, XtY, XtX, tau2, sigma2)
}

blassoconditional_coupled <- function(Y, X, XtY, XtX, tau21, tau22, sigma21, sigma22) {
    .Call('_debiasedmcmc_blassoconditional_coupled', PACKAGE = 'debiasedmcmc', Y, X, XtY, XtX, tau21, tau22, sigma21, sigma22)
}

logcosh <- function(x) {
    .Call('_debiasedmcmc_logcosh', PACKAGE = 'debiasedmcmc', x)
}

gaussian_max_couplingC <- function(mu1, mu2, Sigma1, Sigma2) {
    .Call('_debiasedmcmc_gaussian_max_couplingC', PACKAGE = 'debiasedmcmc', mu1, mu2, Sigma1, Sigma2)
}

gaussian_max_coupling_cholesky <- function(mu1, mu2, Cholesky1, Cholesky2, Cholesky_inverse1, Cholesky_inverse2) {
    .Call('_debiasedmcmc_gaussian_max_coupling_cholesky', PACKAGE = 'debiasedmcmc', mu1, mu2, Cholesky1, Cholesky2, Cholesky_inverse1, Cholesky_inverse2)
}

xbeta_ <- function(X, beta) {
    .Call('_debiasedmcmc_xbeta_', PACKAGE = 'debiasedmcmc', X, beta)
}

w_rejsamplerC <- function(beta1, beta2, X) {
    .Call('_debiasedmcmc_w_rejsamplerC', PACKAGE = 'debiasedmcmc', beta1, beta2, X)
}

w_max_couplingC <- function(beta1, beta2, X) {
    .Call('_debiasedmcmc_w_max_couplingC', PACKAGE = 'debiasedmcmc', beta1, beta2, X)
}

estimator_bin <- function(c_chains, component, lower, upper, k, K) {
    .Call('_debiasedmcmc_estimator_bin', PACKAGE = 'debiasedmcmc', c_chains, component, lower, upper, k, K)
}

get_measure_ <- function(c_chains, k, m) {
    .Call('_debiasedmcmc_get_measure_', PACKAGE = 'debiasedmcmc', c_chains, k, m)
}

rinvgaussian_c <- function(n, mu, lambda) {
    .Call('_debiasedmcmc_rinvgaussian_c', PACKAGE = 'debiasedmcmc', n, mu, lambda)
}

rinvgaussian_coupled_c <- function(mu1, mu2, lambda1, lambda2) {
    .Call('_debiasedmcmc_rinvgaussian_coupled_c', PACKAGE = 'debiasedmcmc', mu1, mu2, lambda1, lambda2)
}

rcouplbern2 <- function(p1, p2) {
    .Call('_debiasedmcmc_rcouplbern2', PACKAGE = 'debiasedmcmc', p1, p2)
}

ising_sum_ <- function(state) {
    .Call('_debiasedmcmc_ising_sum_', PACKAGE = 'debiasedmcmc', state)
}

ising_gibbs_sweep_ <- function(state, proba_beta) {
    .Call('_debiasedmcmc_ising_gibbs_sweep_', PACKAGE = 'debiasedmcmc', state, proba_beta)
}

ising_coupled_gibbs_sweep_ <- function(state1, state2, proba_beta) {
    .Call('_debiasedmcmc_ising_coupled_gibbs_sweep_', PACKAGE = 'debiasedmcmc', state1, state2, proba_beta)
}

ising_two2one_ <- function(ix, iy, size) {
    .Call('_debiasedmcmc_ising_two2one_', PACKAGE = 'debiasedmcmc', ix, iy, size)
}

ising_one2two_ <- function(location, size) {
    .Call('_debiasedmcmc_ising_one2two_', PACKAGE = 'debiasedmcmc', location, size)
}

ising_locationneighbour_ <- function(location, ineighbour, size) {
    .Call('_debiasedmcmc_ising_locationneighbour_', PACKAGE = 'debiasedmcmc', location, ineighbour, size)
}

sigma_ <- function(X, w) {
    .Call('_debiasedmcmc_sigma_', PACKAGE = 'debiasedmcmc', X, w)
}

m_sigma_function_ <- function(omega, X, invB, KTkappaplusinvBtimesb) {
    .Call('_debiasedmcmc_m_sigma_function_', PACKAGE = 'debiasedmcmc', omega, X, invB, KTkappaplusinvBtimesb)
}

rmvnorm <- function(nsamples, mean, covariance) {
    .Call('_debiasedmcmc_rmvnorm', PACKAGE = 'debiasedmcmc', nsamples, mean, covariance)
}

rmvnorm_cholesky <- function(nsamples, mean, cholesky) {
    .Call('_debiasedmcmc_rmvnorm_cholesky', PACKAGE = 'debiasedmcmc', nsamples, mean, cholesky)
}

dmvnorm <- function(x, mean, covariance) {
    .Call('_debiasedmcmc_dmvnorm', PACKAGE = 'debiasedmcmc', x, mean, covariance)
}

dmvnorm_cholesky_inverse <- function(x, mean, cholesky_inverse) {
    .Call('_debiasedmcmc_dmvnorm_cholesky_inverse', PACKAGE = 'debiasedmcmc', x, mean, cholesky_inverse)
}

beta2e_ <- function(beta, C) {
    .Call('_debiasedmcmc_beta2e_', PACKAGE = 'debiasedmcmc', beta, C)
}

cut_in_fifth_ <- function(x) {
    .Call('_debiasedmcmc_cut_in_fifth_', PACKAGE = 'debiasedmcmc', x)
}

propensity_module2_loglik2_ <- function(theta1s, theta2s, X, C, Y) {
    .Call('_debiasedmcmc_propensity_module2_loglik2_', PACKAGE = 'debiasedmcmc', theta1s, theta2s, X, C, Y)
}

prune_ <- function(df) {
    .Call('_debiasedmcmc_prune_', PACKAGE = 'debiasedmcmc', df)
}

rnorm_reflectionmax_ <- function(mu1, mu2, Sigma_chol, inv_Sigma_chol) {
    .Call('_debiasedmcmc_rnorm_reflectionmax_', PACKAGE = 'debiasedmcmc', mu1, mu2, Sigma_chol, inv_Sigma_chol)
}

sample_pair01 <- function(selection) {
    .Call('_debiasedmcmc_sample_pair01', PACKAGE = 'debiasedmcmc', selection)
}

marginal_likelihood_c_2 <- function(selection, X, Y, Y2, g) {
    .Call('_debiasedmcmc_marginal_likelihood_c_2', PACKAGE = 'debiasedmcmc', selection, X, Y, Y2, g)
}

