# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gaussian_max_couplingC <- function(mu1, mu2, Sigma1, Sigma2) {
    .Call('debiasedmcmc_gaussian_max_couplingC', PACKAGE = 'debiasedmcmc', mu1, mu2, Sigma1, Sigma2)
}

gaussian_max_coupling_cholesky <- function(mu1, mu2, Cholesky1, Cholesky2, Cholesky_inverse1, Cholesky_inverse2) {
    .Call('debiasedmcmc_gaussian_max_coupling_cholesky', PACKAGE = 'debiasedmcmc', mu1, mu2, Cholesky1, Cholesky2, Cholesky_inverse1, Cholesky_inverse2)
}

xbeta_ <- function(X, beta) {
    .Call('debiasedmcmc_xbeta_', PACKAGE = 'debiasedmcmc', X, beta)
}

w_rejsamplerC <- function(beta1, beta2, X) {
    .Call('debiasedmcmc_w_rejsamplerC', PACKAGE = 'debiasedmcmc', beta1, beta2, X)
}

estimator_bin <- function(c_chains, component, lower, upper, k, K) {
    .Call('debiasedmcmc_estimator_bin', PACKAGE = 'debiasedmcmc', c_chains, component, lower, upper, k, K)
}

sigma_ <- function(X, w) {
    .Call('debiasedmcmc_sigma_', PACKAGE = 'debiasedmcmc', X, w)
}

m_sigma_function_ <- function(omega, X, invB, KTkappaplusinvBtimesb) {
    .Call('debiasedmcmc_m_sigma_function_', PACKAGE = 'debiasedmcmc', omega, X, invB, KTkappaplusinvBtimesb)
}

rmvnorm <- function(nsamples, mean, covariance) {
    .Call('debiasedmcmc_rmvnorm', PACKAGE = 'debiasedmcmc', nsamples, mean, covariance)
}

rmvnorm_cholesky <- function(nsamples, mean, cholesky) {
    .Call('debiasedmcmc_rmvnorm_cholesky', PACKAGE = 'debiasedmcmc', nsamples, mean, cholesky)
}

dmvnorm <- function(x, mean, covariance) {
    .Call('debiasedmcmc_dmvnorm', PACKAGE = 'debiasedmcmc', x, mean, covariance)
}

dmvnorm_cholesky_inverse <- function(x, mean, cholesky_inverse) {
    .Call('debiasedmcmc_dmvnorm_cholesky_inverse', PACKAGE = 'debiasedmcmc', x, mean, cholesky_inverse)
}

beta2e_ <- function(beta, C) {
    .Call('debiasedmcmc_beta2e_', PACKAGE = 'debiasedmcmc', beta, C)
}

cut_in_fifth_ <- function(x) {
    .Call('debiasedmcmc_cut_in_fifth_', PACKAGE = 'debiasedmcmc', x)
}

propensity_module2_loglik2_ <- function(theta1s, theta2s, X, C, Y) {
    .Call('debiasedmcmc_propensity_module2_loglik2_', PACKAGE = 'debiasedmcmc', theta1s, theta2s, X, C, Y)
}

